version: '3'

services:
  app-server:
    image: devfreitag/persona-crud
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/personadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devFreitag

  database:
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=personadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devFreitag